https://www.siteinexistente123456.com - Erro: HTTPSConnectionPool(host='www.siteinexistente123456.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014B3975DA90>: Failed to resolve 'www.siteinexistente123456.com' ([Errno 11001] getaddrinfo failed)"))
https://httpstat.us/404 - Erro: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
